app:
  sources:
    topic: "AI engineering, LLM applications, machine learning infrastructure"
    entries:
      - id: simon-willison
        type: rss
        url: https://simonwillison.net/atom/everything/
        poll-interval-minutes: 60

#      - id: hacker-news
#        type: rss
#        url: https://hnrss.org/best
#        poll-interval-minutes: 30
#
#      - id: openai-blog
#        type: website
#        url: https://openai.com/blog
#        poll-interval-minutes: 120
